const LANGS = {
  en: {
    flag:'🇺🇸', name:'English',
    nav_about:'About', nav_platforms:'Platforms', nav_vision:'Vision', nav_contact:'Contact', nav_cta:'Get in Touch',
    hero_badge:'AI Agent Company · Est. 2026',
    hero_h1:'New Sense.<br><em>New World.</em>',
    hero_sub:'ROVAVIX pioneers AI agent platforms that connect people with truth, health, opportunity, and accessibility — for everyone, everywhere.',
    hero_btn1:'Explore Platforms', hero_btn2:'Our Story',
    stat1:'Platforms in Development', stat2:'Founded', stat3:'Core Technology', stat4:'Target Market',
    plat_tag:'Our Platforms', plat_title:'Four platforms.<br>One mission.',
    plat_desc:'Each platform is independent yet united by a single belief — AI should make life more truthful, healthier, fairer, and more accessible.',
    status_dev:'In Development', status_live:'Live', learn_more:'Learn more →',
    visit_live:'Visit Live Site →', back_platforms:'← All Platforms',
    aiva_desc:'As AI-generated content floods the internet, AIVA empowers users to distinguish reality from fabrication — building AI literacy and protecting people from misinformation.',
    lifelink_desc:'A lifestyle platform that motivates continuous healthy behaviors through engaging challenges and community. Building lasting habits, one step at a time.',
    spotwork_desc:"Korea's aging population holds untapped potential. SpotWork connects experienced senior workers with companies seeking flexible, short-term talent — redefining the value of experience.",
    jarvis_desc:'A voice-powered AI tool designed to enhance digital accessibility for the elderly and people with disabilities — ensuring no one is left behind in the AI era.',
    about_tag:'About ROVAVIX', about_title:'Technology<br>for people,<br>not the other way.',
    about_p1:'ROVAVIX was founded with a simple conviction: AI should serve the many, not just the few. We pioneer platforms that solve real problems — for seniors, for people with disabilities, for anyone navigating an increasingly complex information landscape.',
    about_p2:'We are a future-oriented AI agent company based in Korea, with global ambitions rooted in human values. ROVAVIX — pioneering and winning with AI.',
    val1_title:'Trust', val1_desc:"We protect people's right to accurate information in an age of AI-generated noise.",
    val2_title:'Inclusion', val2_desc:"Seniors, people with disabilities, and the digitally underserved all deserve access to AI's benefits.",
    val3_title:'Connection', val3_desc:'We bridge people with opportunity, health, and each other through intelligent platforms.',
    val4_title:'Innovation', val4_desc:"Practical innovation that solves real-world problems — not technology for technology's sake.",
    vision_tag:'Vision & Roadmap', vision_title:"Where we're headed.",
    v1_title:'Platform Launch', v1_desc:'Deploy MVP versions of all four platforms. Acquire early users and validate product-market fit in the Korean market.',
    v2_title:'Scale Up', v2_desc:'Deepen platform capabilities, establish revenue models, and target Series A investment to accelerate growth.',
    v3_title:'Global Expansion', v3_desc:'Enter Asian markets and position ROVAVIX as a globally recognized AI agent company with meaningful social impact.',
    contact_tag:'Get In Touch', contact_title:"Let's build the future together.",
    contact_desc:'We welcome investors, partners, and collaborators who share our vision of a more human AI world.'
  },
  ko: {
    flag:'🇰🇷', name:'한국어',
    nav_about:'소개', nav_platforms:'플랫폼', nav_vision:'비전', nav_contact:'문의', nav_cta:'문의하기',
    hero_badge:'AI 에이전트 기업 · 2026년 설립',
    hero_h1:'새로운 감각,<br><em>새로운 세상.</em>',
    hero_sub:'ROVAVIX는 신뢰, 건강, 기회, 접근성을 AI로 연결하는 플랫폼을 개척합니다. 모든 사람을 위해, 어디서나.',
    hero_btn1:'플랫폼 살펴보기', hero_btn2:'회사 소개',
    stat1:'개발 중인 플랫폼', stat2:'설립 연도', stat3:'핵심 기술', stat4:'목표 시장',
    plat_tag:'플랫폼 소개', plat_title:'4개의 플랫폼,<br>하나의 사명.',
    plat_desc:'각 플랫폼은 독립적이지만 하나의 믿음으로 연결됩니다 — AI는 삶을 더 진실되고, 건강하고, 공정하고, 접근하기 쉽게 만들어야 합니다.',
    status_dev:'개발 중', status_live:'운영중', learn_more:'자세히 보기 →',
    visit_live:'라이브 사이트 방문 →', back_platforms:'← 전체 플랫폼',
    aiva_desc:'AI 생성 콘텐츠가 넘쳐나는 시대, AIVA는 사용자 스스로 현실과 가상을 구별할 수 있도록 돕습니다. AI 리터러시를 높이고 정보 왜곡으로부터 사람들을 보호합니다.',
    lifelink_desc:'다양한 챌린지와 커뮤니티를 통해 건강한 행동을 지속적으로 유도하는 라이프스타일 플랫폼. 한 걸음씩, 지속 가능한 습관을 만들어갑니다.',
    spotwork_desc:'빠르게 고령화되는 한국 사회에서 시니어의 경험은 소중한 자원입니다. SpotWork는 고령 인재와 기업을 연결하는 단시간 근로 매칭 플랫폼입니다.',
    jarvis_desc:'음성 인식 AI로 고령자와 장애인의 디지털 접근성을 높이는 도구. AI 시대에 그 누구도 소외되지 않도록 합니다.',
    about_tag:'ROVAVIX 소개', about_title:'기술이 사람을<br>섬기는 세상,<br>그것이 ROVAVIX입니다.',
    about_p1:'ROVAVIX는 하나의 확신으로 설립되었습니다. AI는 소수가 아닌 모두를 위해 존재해야 한다는 것. 우리는 노인, 장애인, 정보 홍수 속에서 길을 잃은 모든 이를 위한 실질적인 해결책을 개척합니다.',
    about_p2:'우리는 한국에서 출발해 글로벌을 향해 나아가는 미래지향적 AI 에이전트 기업입니다. ROVAVIX — AI로 개척하고 승리합니다.',
    val1_title:'신뢰 (Trust)', val1_desc:'AI 생성 정보의 홍수 속에서 사람들이 정확한 정보를 접할 권리를 지킵니다.',
    val2_title:'포용 (Inclusion)', val2_desc:'고령자, 장애인, 디지털 소외 계층 모두가 AI의 혜택을 누릴 수 있어야 합니다.',
    val3_title:'연결 (Connection)', val3_desc:'사람과 기회, 건강, 그리고 서로를 AI로 자연스럽게 이어줍니다.',
    val4_title:'혁신 (Innovation)', val4_desc:'현장의 문제를 해결하는 실용적 혁신. 기술을 위한 기술이 아닌, 사람을 위한 기술입니다.',
    vision_tag:'비전 & 로드맵', vision_title:'ROVAVIX가 나아갈 방향.',
    v1_title:'플랫폼 런칭', v1_desc:'4개 플랫폼 MVP 배포. 초기 사용자 확보 및 국내 시장 제품-시장 적합성 검증.',
    v2_title:'스케일업', v2_desc:'플랫폼 고도화 및 수익 모델 확립. 시리즈 A 투자 유치를 통한 성장 가속화.',
    v3_title:'글로벌 도약', v3_desc:'아시아 시장 진출 및 사회적 임팩트를 갖춘 글로벌 AI 에이전트 기업으로 도약.',
    contact_tag:'문의하기', contact_title:'함께 미래를 만들어가요.',
    contact_desc:'더 인간적인 AI 세상이라는 비전을 공유하는 투자자, 파트너, 협력자를 환영합니다.'
  },
  ja: {
    flag:'🇯🇵', name:'日本語',
    nav_about:'概要', nav_platforms:'プラットフォーム', nav_vision:'ビジョン', nav_contact:'お問合せ', nav_cta:'お問合せ',
    hero_badge:'AIエージェント企業 · 2026年設立',
    hero_h1:'新しい感覚、<br><em>新しい世界。</em>',
    hero_sub:'ROVAVIXは、信頼・健康・機会・アクセシビリティをAIでつなぐプラットフォームを開拓します。すべての人のために、どこでも。',
    hero_btn1:'プラットフォームを見る', hero_btn2:'会社紹介',
    stat1:'開発中のプラットフォーム', stat2:'設立年', stat3:'コア技術', stat4:'目標市場',
    plat_tag:'プラットフォーム', plat_title:'4つのプラットフォーム、<br>1つのミッション。',
    plat_desc:'各プラットフォームは独立しながらも、一つの信念で結ばれています — AIは生活をより誠実で、健康的で、公平で、アクセスしやすくするべきだという信念。',
    status_dev:'開発中', status_live:'運用中', learn_more:'詳しく見る →',
    visit_live:'ライブサイトを見る →', back_platforms:'← すべてのプラットフォーム',
    aiva_desc:'AIが生成したコンテンツが溢れる時代に、AIVAはユーザーが現実と虚構を見分ける力を育みます。',
    lifelink_desc:'チャレンジとコミュニティを通じて継続的な健康行動を促すライフスタイルプラットフォーム。',
    spotwork_desc:'急速に高齢化する社会において、シニアの経験は貴重な資源です。SpotWorkはシニア人材と企業をつなぐ短時間勤務マッチングプラットフォームです。',
    jarvis_desc:'音声認識AIで高齢者や障害者のデジタルアクセシビリティを高めるツール。AI時代に誰も取り残されないために。',
    about_tag:'ROVAVIXについて', about_title:'技術は人のために、<br>その逆ではない。',
    about_p1:'ROVAVIXはシンプルな確信から生まれました。AIは一部の人ではなく、すべての人のために存在すべきだということ。',
    about_p2:'私たちは韓国を起点に、人間的な価値を基盤としてグローバルを目指す未来志向のAIエージェント企業です。',
    val1_title:'信頼', val1_desc:'AI生成情報が溢れる時代に、人々が正確な情報に接する権利を守ります。',
    val2_title:'包摂', val2_desc:'高齢者、障害者、デジタル格差を抱える方々もAIの恩恵を受けられるべきです。',
    val3_title:'つながり', val3_desc:'人と機会、健康、そして互いをAIで自然につなぎます。',
    val4_title:'革新', val4_desc:'現場の問題を解決する実用的な革新。人のための技術です。',
    vision_tag:'ビジョン & ロードマップ', vision_title:'私たちが向かう先。',
    v1_title:'プラットフォーム立ち上げ', v1_desc:'4つのプラットフォームのMVPをリリース。初期ユーザーを獲得します。',
    v2_title:'スケールアップ', v2_desc:'プラットフォームの高度化と収益モデルの確立。シリーズA資金調達を目指します。',
    v3_title:'グローバル展開', v3_desc:'アジア市場に進出し、グローバルAIエージェント企業として成長します。',
    contact_tag:'お問い合わせ', contact_title:'共に未来を作りましょう。',
    contact_desc:'より人間的なAIの世界というビジョンを共有する投資家・パートナー・協力者を歓迎します。'
  },
  zh: {
    flag:'🇨🇳', name:'中文',
    nav_about:'关于我们', nav_platforms:'平台', nav_vision:'愿景', nav_contact:'联系我们', nav_cta:'联系我们',
    hero_badge:'AI智能体公司 · 2026年成立',
    hero_h1:'新感知，<br><em>新世界。</em>',
    hero_sub:'ROVAVIX 开拓通过AI连接信任、健康、机会与无障碍的平台——为每一个人，在每一个地方。',
    hero_btn1:'探索平台', hero_btn2:'了解我们',
    stat1:'开发中的平台', stat2:'成立年份', stat3:'核心技术', stat4:'目标市场',
    plat_tag:'我们的平台', plat_title:'四个平台，<br>一个使命。',
    plat_desc:'每个平台相互独立，却共同秉持一个信念——AI应让生活更真实、更健康、更公平、更易获取。',
    status_dev:'开发中', status_live:'运营中', learn_more:'了解更多 →',
    visit_live:'访问上线网站 →', back_platforms:'← 所有平台',
    aiva_desc:'在AI生成内容泛滥的时代，AIVA帮助用户辨别现实与虚构，提升AI素养，保护人们免受虚假信息的侵害。',
    lifelink_desc:'通过挑战和社区激励持续健康行为的生活方式平台，一步一步建立持久的健康习惯。',
    spotwork_desc:'在快速老龄化的社会中，老年人的经验是宝贵的资源。SpotWork是连接资深老年工作者与企业的灵活用工匹配平台。',
    jarvis_desc:'通过语音识别AI提升老年人和残障人士数字无障碍能力的工具，确保在AI时代没有人被落下。',
    about_tag:'关于ROVAVIX', about_title:'技术服务于人，<br>而非相反。',
    about_p1:'ROVAVIX秉持一个简单的信念：AI应该服务于大多数人，而不仅仅是少数人。我们开拓解决实际问题的平台。',
    about_p2:'我们是一家以韩国为起点、以人类价值为根基、面向全球的未来导向AI智能体公司。',
    val1_title:'信任', val1_desc:'在AI生成信息泛滥的时代，保护人们获取准确信息的权利。',
    val2_title:'包容', val2_desc:'老年人、残障人士和数字弱势群体都应享有AI带来的惠益。',
    val3_title:'连接', val3_desc:'通过智能平台将人与机会、健康以及彼此自然连接。',
    val4_title:'创新', val4_desc:'解决实际问题的务实创新，而非为技术而技术。',
    vision_tag:'愿景与路线图', vision_title:'我们前行的方向。',
    v1_title:'平台启动', v1_desc:'发布四个平台的MVP版本，获取早期用户，验证产品市场契合度。',
    v2_title:'规模化扩张', v2_desc:'深化平台能力，建立收入模式，目标完成A轮融资。',
    v3_title:'全球扩张', v3_desc:'进入亚洲市场，将ROVAVIX打造为具有深远社会影响力的全球AI智能体企业。',
    contact_tag:'联系我们', contact_title:'共同构建未来。',
    contact_desc:'欢迎与我们共享愿景的投资者、合作伙伴和协作者。'
  },
  es: {
    flag:'🇪🇸', name:'Español',
    nav_about:'Nosotros', nav_platforms:'Plataformas', nav_vision:'Visión', nav_contact:'Contacto', nav_cta:'Contáctanos',
    hero_badge:'Empresa de Agentes IA · Est. 2026',
    hero_h1:'Nuevo Sentido.<br><em>Nuevo Mundo.</em>',
    hero_sub:'ROVAVIX desarrolla plataformas de agentes IA que conectan a las personas con la verdad, la salud, las oportunidades y la accesibilidad — para todos, en todas partes.',
    hero_btn1:'Explorar Plataformas', hero_btn2:'Nuestra Historia',
    stat1:'Plataformas en Desarrollo', stat2:'Fundación', stat3:'Tecnología Central', stat4:'Mercado Objetivo',
    plat_tag:'Nuestras Plataformas', plat_title:'Cuatro plataformas.<br>Una misión.',
    plat_desc:'Cada plataforma es independiente pero unida por una sola creencia: la IA debe hacer la vida más veraz, saludable, justa y accesible.',
    status_dev:'En Desarrollo', status_live:'En Operación', learn_more:'Saber más →',
    visit_live:'Visitar sitio en vivo →', back_platforms:'← Todas las plataformas',
    aiva_desc:'A medida que el contenido generado por IA inunda internet, AIVA capacita a los usuarios para distinguir la realidad de la fabricación.',
    lifelink_desc:'Una plataforma de estilo de vida que motiva comportamientos saludables continuos a través de desafíos y comunidad.',
    spotwork_desc:'La envejecida población de Corea tiene un potencial sin explotar. SpotWork conecta a trabajadores mayores con empresas que buscan talento flexible.',
    jarvis_desc:'Una herramienta de IA impulsada por voz para mejorar la accesibilidad digital de personas mayores y con discapacidades.',
    about_tag:'Sobre ROVAVIX', about_title:'Tecnología para las personas,<br>no al revés.',
    about_p1:'ROVAVIX fue fundada con una convicción simple: la IA debe servir a muchos, no solo a pocos. Desarrollamos plataformas que resuelven problemas reales.',
    about_p2:'Somos una empresa de agentes de IA orientada al futuro con sede en Corea, con ambiciones globales arraigadas en valores humanos.',
    val1_title:'Confianza', val1_desc:'Protegemos el derecho de las personas a la información precisa.',
    val2_title:'Inclusión', val2_desc:'Las personas mayores, con discapacidades y digitalmente excluidas merecen acceso a los beneficios de la IA.',
    val3_title:'Conexión', val3_desc:'Conectamos a las personas con oportunidades, salud y entre sí.',
    val4_title:'Innovación', val4_desc:'Innovación práctica que resuelve problemas del mundo real.',
    vision_tag:'Visión y Hoja de Ruta', vision_title:'Hacia dónde nos dirigimos.',
    v1_title:'Lanzamiento', v1_desc:'Desplegar versiones MVP de las cuatro plataformas y adquirir usuarios iniciales.',
    v2_title:'Escala', v2_desc:'Profundizar capacidades, establecer modelos de ingresos y apuntar a inversión de Serie A.',
    v3_title:'Expansión Global', v3_desc:'Entrar en mercados asiáticos y posicionar a ROVAVIX como empresa global de agentes IA.',
    contact_tag:'Contáctanos', contact_title:'Construyamos el futuro juntos.',
    contact_desc:'Damos la bienvenida a inversores, socios y colaboradores que compartan nuestra visión.'
  },
  de: {
    flag:'🇩🇪', name:'Deutsch',
    nav_about:'Über uns', nav_platforms:'Plattformen', nav_vision:'Vision', nav_contact:'Kontakt', nav_cta:'Kontakt aufnehmen',
    hero_badge:'KI-Agenten-Unternehmen · Gegr. 2026',
    hero_h1:'Neues Gespür.<br><em>Neue Welt.</em>',
    hero_sub:'ROVAVIX entwickelt KI-Agenten-Plattformen, die Menschen mit Wahrheit, Gesundheit, Chancen und Barrierefreiheit verbinden — für alle, überall.',
    hero_btn1:'Plattformen entdecken', hero_btn2:'Unsere Geschichte',
    stat1:'Plattformen in Entwicklung', stat2:'Gründungsjahr', stat3:'Kerntechnologie', stat4:'Zielmarkt',
    plat_tag:'Unsere Plattformen', plat_title:'Vier Plattformen.<br>Eine Mission.',
    plat_desc:'Jede Plattform ist eigenständig, aber durch eine Überzeugung verbunden: KI soll das Leben wahrhaftiger, gesünder, fairer und zugänglicher machen.',
    status_dev:'In Entwicklung', status_live:'Im Betrieb', learn_more:'Mehr erfahren →',
    visit_live:'Live-Website besuchen →', back_platforms:'← Alle Plattformen',
    aiva_desc:'Während KI-generierte Inhalte das Internet überfluten, befähigt AIVA Nutzer, Realität von Fiktion zu unterscheiden.',
    lifelink_desc:'Eine Lifestyle-Plattform, die durch Challenges und Community kontinuierlich gesundes Verhalten fördert.',
    spotwork_desc:'Koreas alternde Bevölkerung birgt ungenutztes Potenzial. SpotWork verbindet erfahrene ältere Arbeitnehmer mit Unternehmen.',
    jarvis_desc:'Ein sprachgesteuertes KI-Tool, das die digitale Barrierefreiheit für ältere Menschen und Menschen mit Behinderungen verbessert.',
    about_tag:'Über ROVAVIX', about_title:'Technologie für Menschen,<br>nicht umgekehrt.',
    about_p1:'ROVAVIX wurde mit einer einfachen Überzeugung gegründet: KI sollte vielen dienen, nicht nur wenigen. Wir entwickeln Plattformen, die reale Probleme lösen.',
    about_p2:'Wir sind ein zukunftsorientiertes KI-Agenten-Unternehmen mit Sitz in Korea und globalen Ambitionen.',
    val1_title:'Vertrauen', val1_desc:'Wir schützen das Recht der Menschen auf genaue Informationen.',
    val2_title:'Inklusion', val2_desc:'Senioren, Menschen mit Behinderungen und digital Benachteiligte verdienen Zugang zu KI.',
    val3_title:'Verbindung', val3_desc:'Wir verbinden Menschen mit Chancen, Gesundheit und miteinander.',
    val4_title:'Innovation', val4_desc:'Praktische Innovation, die reale Probleme löst.',
    vision_tag:'Vision & Roadmap', vision_title:'Wohin wir uns bewegen.',
    v1_title:'Plattform-Launch', v1_desc:'Bereitstellung der MVP-Versionen aller vier Plattformen und Gewinnung früher Nutzer.',
    v2_title:'Skalierung', v2_desc:'Plattformfähigkeiten vertiefen, Erlösmodelle etablieren und Series-A anstreben.',
    v3_title:'Globale Expansion', v3_desc:'Eintritt in asiatische Märkte und Positionierung von ROVAVIX als globales KI-Unternehmen.',
    contact_tag:'Kontakt', contact_title:'Lass uns gemeinsam die Zukunft gestalten.',
    contact_desc:'Wir heißen Investoren, Partner und Mitstreiter willkommen, die unsere Vision teilen.'
  }
};
